[package]
name = "amazon-music-fixer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
regex = "1.7.1"
text-colorizer = "1.0.0"
walkdir = "2.3.2"
